name: Tests
on: [push, pull_request]

jobs:
  frontend-unit-test:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint -w ./packages/frontend/display

      - name: Run unit tests
        run: npm run test:unit:cov -w ./packages/frontend/display

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: Frontend Unit Tests
          file: ./packages/frontend/display/coverage/lcov.info
          parallel: true

  frontend-acceptance-test:
    name: Frontend Acceptance Tests
    runs-on: ubuntu-latest
    needs: frontend-unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration:cov -w ./packages/frontend/display

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: Frontend Integration Tests
          parallel: true

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [frontend-unit-test, frontend-acceptance-test]

    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
